spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
      #jdbc:h2:tcp://localhost/~/jpashop
     #jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
# 로그를 찍어줌